version: 2.1

parameters:
  poetry-version:
    type: string
    default: "1.8.3"
  old-poetry-version:
    type: string
    default: "1.1.14"
  py36-tag:
    type: string
    default: "py36"
  py38-tag:
    type: string
    default: "py38"
  py310-tag:
    type: string
    default: "py310.py312"


executors:
  focal:
    docker:
      - image: aotuai/brainframe-cli-env-20.04:4bbabb5--no-cache
  bionic:
    docker:
      - image: aotuai/brainframe-cli-env-18.04:4bbabb5--no-cache


workflows:
  lint:
    jobs:
      - lint-approval:
          type: approval
          requires: []
      - lint:
          requires:
            - lint-approval
  build-and-test-deb:
    jobs:
      - build-approval:
          type: approval
          requires: []
      - build-deb:
          requires:
            - build-approval
          matrix:
            parameters:
              os: [bionic, focal]
              poetry-version:
                - << pipeline.parameters.old-poetry-version >>
                - << pipeline.parameters.poetry-version >>
            exclude:
              - os: bionic
                poetry-version: << pipeline.parameters.poetry-version >>
              - os: focal
                poetry-version: << pipeline.parameters.old-poetry-version >>
      - test-installation-deb:
          requires:
            - build-deb
  build-and-upload-binary:
    jobs:
      - build-binary-approval:
          type: approval
          requires: []
      - build-binary:
          requires:
            - build-binary-approval
      - test-installation-binary:
          requires:
            - build-binary
      - push-to-staging-approval:
          type: approval
          requires:
            - build-binary
            - test-installation-binary
      - upload-binary:
          name: upload-binary-staging
          context: aws-staging
          requires:
            - push-to-staging-approval
      - push-to-production-approval:
          type: approval
          requires:
            - upload-binary-staging
      - upload-binary:
          name: upload-binary-production
          context: aws
          requires:
            - push-to-production-approval
          filters:
            # Ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # Run only when a tag is created
            tags:
              only: /^v.+\..+\..+/
  pypi-deploy:
    jobs:
      - push-to-pypi-approval:
          type: approval
          requires: []
      - upload-to-pypi:
          requires:
            - push-to-pypi-approval
          filters:
            # Ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # Run only when a tag is created
            tags:
              only: /^v.+\..+\..+/
  installation-tests:
    jobs:
      - test-approval:
          type: approval
          requires: []
      - test-installation-source:
          requires:
            - test-approval


jobs:
  lint:
    docker:
      - image: aotuai/brainframe-cli-env-20.04:7d3e7d
    steps:
      - checkout
      - run: cp /deployment/* ~/project/
      - run:
          working_directory: /deployment
          command: poetry run isort --check ~/project/
      - run:
          working_directory: /deployment
          command: poetry run black --check ~/project/
      - run: 
          working_directory: /deployment
          command: MYPYPATH=~/project/ poetry run mypy --config-file ~/project/mypy.ini -p "brainframe.cli"

  build-deb:
    parameters:
      os:
        type: executor
      poetry-version:
        type: string
    executor: << parameters.os >>
    steps:
      - install-poetry:
          poetry-version: << parameters.poetry-version >>
      - checkout
      - run:
          command: |
            case "$CIRCLE_JOB" in
              *bionic*)
                echo 'export PY_TAG="<< pipeline.parameters.py36-tag >>"' >> $BASH_ENV
                ;;
              *focal*)
                echo 'export PY_TAG="<< pipeline.parameters.py38-tag >>"' >> $BASH_ENV
                ;;
              *)
                echo 'export PY_TAG="<< pipeline.parameters.py310-tag >>"' >> $BASH_ENV
                ;;
            esac
            source $BASH_ENV
      - run:
          working_directory: ~/project/
          command: |
            cp -r package/debian .
            cp package/setup.py .
            cp package/system_package_defaults.yaml brainframe/cli/defaults.yaml
            cp deployment/pyproject.toml.${PY_TAG} pyproject.toml
            cp deployment/poetry.lock.${PY_TAG} poetry.lock
      - run:
          working_directory: ~/project/
          command: |
            mk-build-deps --install debian/control
            poetry export --output requirements.txt
      - run: dpkg-buildpackage --unsigned-source --unsigned-changes --build=binary
      - run: mkdir dist
      - run: |
          export CODENAME=$(lsb_release --codename --short)
          mv ../brainframe-cli*.deb dist/brainframe-cli-${CODENAME}.deb
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  test-installation-deb:
    docker:
      - image: aotuai/test-ubuntu-20.04:7d3e7d
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            apt-get -y install /tmp/workspace/dist/brainframe-cli-focal.deb
            export LOGNAME=root
            brainframe install --noninteractive
            brainframe compose up -d
      - assert-core-container-running
      - assert-core-responds-to-http
      - run: brainframe uninstall --noninteractive
      - assert-uninstalled-data-preserved:
          install_path: /usr/share/brainframe
          data_path: /var/lib/brainframe

  upload-to-pypi:
    docker:
      - image: aotuai/brainframe-cli-env-20.04:7d3e7d
    environment:
      POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
    steps:
      - checkout
      - run: poetry build
      - run: POETRY_HTTP_BASIC_PYPI_PASSWORD=${PYPI_PASSWORD} poetry publish

  test-installation-source:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: medium
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -y install python3-pip python3-dev curl git
      - checkout
      - install-poetry
      - run:
          command: |
            case "$CIRCLE_JOB" in
              *bionic*)
                echo 'export PY_TAG="<< pipeline.parameters.py36-tag >>"' >> $BASH_ENV
                ;;
              *focal*)
                echo 'export PY_TAG="<< pipeline.parameters.py38-tag >>"' >> $BASH_ENV
                ;;
              *)
                echo 'export PY_TAG="<< pipeline.parameters.py310-tag >>"' >> $BASH_ENV
                ;;
            esac
            source $BASH_ENV
      - run:
          working_directory: ~/project/
          command: |
              cp deployment/pyproject.toml.${PY_TAG} pyproject.toml
              cp deployment/poetry.lock.${PY_TAG} poetry.lock
              sudo $(which poetry) install
      - run: sudo $(which poetry) run brainframe install --noninteractive
      - run: sudo $(which poetry) run brainframe compose up -d
      - assert-core-container-running
      - assert-core-responds-to-http
      - run: sudo $(which poetry) run brainframe uninstall --noninteractive
      - assert-uninstalled-data-preserved:
          install_path: /usr/local/share/brainframe
          data_path: /var/local/brainframe

  build-binary:
    docker:
      - image: aotuai/brainframe-cli-env-20.04:7d3e7d
    environment:
      PYTHONIOENCODING: utf8
    steps:
      - checkout
      - run:
          working_directory: /deployment
          command: |
              cp /deployment/* ~/project/
              apt-get update
              apt-get install -y binutils
              poetry config virtualenvs.in-project true
              $(which poetry) install --no-root
      - run:
          working_directory: /deployment
          command: |
              VENV_PATH=$(poetry env info --path)
              cd ~/project/
              PYTHONPATH=$PYTHONPATH:. $VENV_PATH/bin/python -m PyInstaller package/main.spec
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  upload-binary:
    docker:
      - image: aotuai/brainframe-cli-env-20.04:7d3e7d
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          command: |
            export PYTHON_VERSION=$(python --version 2>&1 | cut -d" " -f2)
            case "${PYTHON_VERSION%.*}" in
              3.6)
                echo 'export PY_TAG="<< pipeline.parameters.py36-tag >>"' >> $BASH_ENV
                ;;
              3.8)
                echo 'export PY_TAG="<< pipeline.parameters.py38-tag >>"' >> $BASH_ENV
                ;;
              *)
                echo 'export PY_TAG="<< pipeline.parameters.py310-tag >>"' >> $BASH_ENV
                ;;
            esac
            source $BASH_ENV
      - run:
          command: |
             cp deployment/pyproject.toml.${PY_TAG} pyproject.toml
             cp deployment/poetry.lock.${PY_TAG} poetry.lock
             poetry install
      - run: poetry run python package/upload_binary.py --binary-path /tmp/workspace/dist/brainframe

  test-installation-binary:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: medium
    steps:
      - run: sudo apt-get update
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo cp /tmp/workspace/dist/brainframe /usr/local/bin/brainframe
      - run: sudo brainframe install --noninteractive
      - run: sudo brainframe compose up -d
      - assert-core-container-running
      - assert-core-responds-to-http
      - run: sudo brainframe uninstall --noninteractive
      - assert-uninstalled-data-preserved:
          install_path: /usr/local/share/brainframe
          data_path: /var/local/brainframe

commands:
  install-poetry:
    parameters:
      poetry-version:
        type: string
        default: << pipeline.parameters.poetry-version >>
    steps:
      - run: >
          curl -sSL https://install.python-poetry.org 
          | python3 - --version << parameters.poetry-version >>
      # Add to the PATH
      - run: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
  assert-core-container-running:
    steps:
      - run:
          name: Check BrainFrame core container is running
          command: |
            until docker container inspect -f {{.State.Running}}  $(docker ps -q -f name="brainframe-core") >/dev/null 2>/dev/null; do
                sleep 0.1;
            done;
            echo "BrainFrame core container is running."
          no_output_timeout: 1m
  assert-core-responds-to-http:
    steps:
      - run:
          name: Check BrainFrame core responds to HTTP requests
          command: |
            until curl -f http://localhost/api/version >/dev/null 2>/dev/null; do
              sleep 0.1;
            done;
            echo "BrainFrame core service is up."
          no_output_timeout: 1m
  assert-uninstalled-data-preserved:
    parameters:
      install_path:
        type: string
      data_path:
        type: string
    steps:
      - run:
          name: Check BrainFrame is uninstalled, but data is preserved
          command: |
            stat << parameters.data_path >>
            ! stat << parameters.install_path >>
            # Check that the images have been removed
            ! docker image ls | grep aotuai/brainframe_core
