version: 2.1

workflows:
  lint:
    jobs:
      - lint
  deploy:
    jobs:
      - upload_to_pypi:
          filters:
            # Ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # Run only when a tag is created
            tags:
              only: /^v.+\..+\..+/
  test:
    jobs:
      - test_installation


jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          | python3 - --version 1.1.0"
      - run: poetry install --no-root
      - run: poetry run isort --check .
      - run: poetry run black --check .
      - run: poetry run mypy -p "brainframe.cli"
  upload_to_pypi:
    docker:
      - image: circleci/python:3.6
    environment:
      POETRY_HTTP_BASIC_PYPI_USERNAME: __token__

    steps:
      - checkout
      - run: "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          | python3 - --version 1.1.0"
      - run: poetry build
      - run: POETRY_HTTP_BASIC_PYPI_PASSWORD=${PYPI_PASSWORD} poetry publish
  test_installation:
    machine:
      - image: "ubuntu:18.04"
    steps:
      - apt-get update
      - apt-get install python3 python3-dev curl
      - checkout
      - run: "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          | python3 - --version 1.1.0"
      - run: poetry install --no-root
      - run: sudo /root/.poetry/bin/poetry run brainframe install --noninteractive
