#!/bin/bash
#
# Copyright (c) 2024 AOTU, Inc.  All rights reserved. Contains Dilili Labs Proprietary Information. RESTRICTED COMPUTER SOFTWARE.  LIMITED RIGHTS DATA.
#

CMDLINE=$0
CMD=$1
ARG=$2
ARGS="${@:2}"

DATE=$(date -u +"%Y-%m-%d-%H-%M-%S")

dind_help() {
        echo ""
        echo " ================== DinD test help ================="
        echo " pip install brainframe_cli_v "
        echo " export LOGNAME=root"
        echo " dockerd &"
	echo " python3 -m venv my_venv"
	echo " source my_venv/bin/activate"
        echo " brainframe install"
        echo " brainframe compose down"
        echo " ===================================================="
        echo ""
}

build_ubuntu_docker() {
    local UBUNTU_VERSION=$1
    local ARGS="${@:2}"

    DOCKER_BUILDKIT=1 docker build \
        --file deployment/Dockerfile.ubuntu \
        --build-arg UBUNTU_VERSION="$UBUNTU_VERSION" \
        $ARGS \
        --tag "test-ubuntu-${UBUNTU_VERSION}" \
        .
}

run_docker() {
    local VOLUME=$1
    local WORKDIR=$2
    local IMAGE=$3
    local UBUNTU_VERSION=$4
    local ARG=$6
    local ARGS=${@:7}

    local IMAGE_TAG="${IMAGE}-${UBUNTU_VERSION}"

    if [[ -z "$ARG" ]]; then
	dind_help
        docker run --privileged -it --rm \
            -v ./:$VOLUME \
            -w $WORKDIR \
            "$IMAGE_TAG" \
            bash
    else
        docker run -it --rm \
            -v ./:$VOLUME \
            -w $WORKDIR \
            "$IMAGE_TAG" \
            bash \
	    $ARG \
            "$ARGS"
    fi
}

build_brainframe_cli_env() {
    local DOCKERFILE=$1
    local PYPROJECT=$2
    local POETRYLOCK=$3
    local UBUNTU_VERSION=$4
    local ADDITIONAL_ARGS=${@:5}

    local IMAGE_TAG="brainframe-cli-env-${UBUNTU_VERSION}"

    # Build the Docker image
    DOCKER_BUILDKIT=1 docker build \
        --file "deployment/$DOCKERFILE" \
        --build-arg WORKDIR=/deployment \
        --build-arg UBUNTU_VERSION="$UBUNTU_VERSION" \
        --build-arg PYPROJECT="$PYPROJECT" \
        --build-arg POETRYLOCK="$POETRYLOCK" \
        $ADDITIONAL_ARGS \
        --tag "$IMAGE_TAG" \
        .
}

if [ -z $CMD ] || [ $CMD == '-h' ] || [ $CMD == '--help' ]; then
	echo " Copyright (c) 2024 AOTU, Inc. All rights reserved."
	cat $CMDLINE | grep echo | awk '(NR>11)' | awk '(NR<11)' | awk '{$1= ""; print $0}'
fi

case $CMD in

	help)
	;;

	comments_only)
	echo ┌─────── deploy brainframe-cli ──────────────────────────
	;;

        ubuntu-build)
        echo ├ ./deployment/do ubuntu-build 20.04 # --no-cache
        build_ubuntu_docker $ARGS
        ;;

        ubuntu-run)
        echo │ ./deployment/do ubuntu-run 20.04
        run_docker /brainframe-cli /brainframe-cli/dist test-ubuntu $ARGS
        ;;

	comments_only)
	echo └────────────────────────────────────────────────────────
	echo ┌─────── build brainframe-cli ───────────────────────────
	;;

        brainframe-cli-env-build)
        echo ├ ./deployment/do brainframe-cli-env-build 20.04 # --no-cache
	case $ARG in
		24.04)
		build_brainframe_cli_env Dockerfile.env.py312 pyproject.toml.py310.py312 poetry.lock.py310.py312 $ARGS
		;;

		22.04)
		build_brainframe_cli_env Dockerfile.env pyproject.toml.py310.py312 poetry.lock.py310.py312 $ARGS
		;;

		20.04)
		build_brainframe_cli_env Dockerfile.env pyproject.toml.py38 poetry.lock.py38 $ARGS
		;;

		18.04)
		build_brainframe_cli_env Dockerfile.env pyproject.toml.py38 poetry.lock.py38 $ARGS
		;;
	esac
        ;;

        brainframe-cli-env-run)
        echo │ ./deployment/do brainframe-cli-env-run 20.04
	run_docker /brainframe-cli /deployment brainframe-cli-env $ARGS
        ;;

        brainframe-cli-lint)
        echo │ ./deployment/do brainframe-cli-lint 20.04
        run_docker /brainframe-cli /deployment brainframe-cli-env $ARG bash -c "cp /deployment/* /brainframe-cli/ && poetry run black /brainframe-cli/ && poetry run isort /brainframe-cli/"
        ;;

        brainframe-cli-build)
        echo │ ./deployment/do brainframe-cli-build 20.04
	case $ARG in
		24.04)
		PYTHON_TAG="3.10 3.12"
		;;

		22.04)
		PYTHON_TAG="3.10 3.12"
		;;

		20.04)
		PYTHON_TAG=3.8
		;;

		18.04)
		PYTHON_TAG=
		;;
	esac
        run_docker /brainframe-cli /brainframe-cli brainframe-cli-env $ARG bash -c "cp /deployment/* /brainframe-cli/ && python3 deployment/build.py --versions $PYTHON_TAG"
        ;;

	comments_only)
	echo └────────────────────────────────────────────────────────
	;;

esac

nice_day_var=$((1 + $RANDOM % 10))

if [ $(($nice_day_var%2)) -eq 0 ]; then
	echo
	echo Have a nice day!
else
	echo
	echo You are the best!
fi
