ARG UBUNTU_VERSION=24.04
ARG PYTHON_VERSION=3
ARG POETRY_VERSION=1.8.3
ARG PYPROJECT=pyproject.toml
ARG POETRYLOCK=poetry.lock
ARG WORKDIR=.

FROM ubuntu:${UBUNTU_VERSION}

ARG PYTHON_VERSION
ARG POETRY_VERSION
ARG PYPROJECT
ARG POETRYLOCK
ARG WORKDIR

ENV PYTHON_VERSION=${PYTHON_VERSION}
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.local/bin:$PATH"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-venv \
        python${PYTHON_VERSION}-pip \
        python${PYTHON_VERSION}-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a virtual environment
RUN python${PYTHON_VERSION} -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip and install setuptools and wheel within the virtual environment
RUN pip install --upgrade pip setuptools wheel

# Install Poetry
RUN pip install poetry==${POETRY_VERSION}

WORKDIR $WORKDIR

# Copy just the pyproject.toml and poetry.lock files
COPY ./deployment/${PYPROJECT} ./pyproject.toml
COPY ./deployment/${POETRYLOCK} ./poetry.lock

# Configure Poetry to use the virtual environment
RUN poetry config virtualenvs.create false
RUN poetry config virtualenvs.path /opt/venv

# Install project dependencies
RUN poetry lock
RUN poetry install --no-interaction --no-ansi --no-root --with dev
