ARG UBUNTU_VERSION=24.04
ARG PYTHON_VERSION=3

FROM ubuntu:${UBUNTU_VERSION} AS ubuntu_python

ARG PYTHON_VERSION
ENV PYTHON_VERSION=${PYTHON_VERSION}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-venv \
        python${PYTHON_VERSION}-pip \
        python${PYTHON_VERSION}-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

