INSTALL_PATH = "BRAINFRAME_INSTALL_PATH"
DATA_PATH = "BRAINFRAME_DATA_PATH"

IS_STAGING = "BRAINFRAME_STAGING"
STAGING_USERNAME = "BRAINFRAME_STAGING_USERNAME"
STAGING_PASSWORD = "BRAINFRAME_STAGING_PASSWORD"
